---
title: "Peer relationships interact with cumulative trauma when mental health issues are in stake: Data Analysis Script"
author: "Anna Makova"
date: "10/01/2022"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
---

# Overview

This is the script used for data wrangling and analysis independently conducted for a level 5 statistics course at the University of Glasgow.

Title: **Peer relationships interact with cumulative trauma when mental health issues are in stake**. 
Grade: 21/22

## Introduction 

A second sensitive period of brain development, adolescence, is characterized by increased plasticity which is instrumental for adapting to challenges linked to this developmental phase (Lee et al., 2014). Unfortunately, this increased plasticity also leads to a greater susceptibility to negative effects which may be reflected in the emergence of mental illnesses at the beginning of adolescence (Lee et al., 2014). The prevalence of mental health issues in the adolescent population has been increasing over the past decade with current prevalence of depression symptoms at 17% (Keyes et al., 2019; Klasen et al., 2015). Furthermore, depression often co-occurs with anxiety (Melton et al., 2016) and PTSD symptoms (Andrews et al., 2015) in youth, which can lead to more severe consequences on adolescents’ lives and wellbeing (Melton et al., 2016). 
Trauma and cumulative life adversities during adolescence can have lasting effects on the functioning of the hypothalamic–pituitary–adrenal axis, which in turn affects mental health (Koss and Gunnar, 2018). Environmental adversities like living in poverty or experiencing food insecurity are detrimental to adolescents’ mental health (Ke and Ford-Jones, 2015; McIntyre et al., 2013; Romo et al., 2016; Slopen et al., 2010). Trauma like abuse, racial discrimination, or living with an adult suffering from alcohol use disorder further increase chances of developing a mental disorder in youth, especially in youth from disadvantaged backgrounds (Andrews et al., 2015; Jose and Cherayi, 2020; Myers et al., 2015; Raitasalo et al., 2019). However, a feeling of belonging to a community can alleviate some of the burden on mental health generated by food insecurity and other life adversities (Martin et al., 2016).
Social support has positive effects on mental health of the adolescent population; it predicts less depressive symptoms, regardless of age, gender, or race (Klasen et al., 2015; Vaughan et al., 2010). Strong friendships predict more psychosocial resilience (Harmelen et al., 2017). A sense of connectedness to peers at school is also associated with better wellbeing and mental health (Moore et al., 2018). Furthermore, peer support lower social anxiety of adolescents who have been bullied (Coyle et al., 2021). To see if this pattern is generalizable to other childhood adversities, this study will test whether peer relationships mediate the effects of cumulative adversities in early life on mental health. 


